// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Database;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230619152655_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebAPI.Database.Entities.GroupImage", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GroupId");

                    b.Property<string>("GroupDate")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("GroupDate");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("GroupName");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupImages");
                });

            modelBuilder.Entity("WebAPI.Database.Entities.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImageId");

                    b.Property<string>("FileImage")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("FileImage");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GroupId");

                    b.Property<string>("ImageDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ImageId");

                    b.HasIndex("GroupId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("WebAPI.Database.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebAPI.Database.Entities.GroupImage", b =>
                {
                    b.HasOne("WebAPI.Database.Entities.User", "CreateBy")
                        .WithMany("GroupImage")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreateBy");
                });

            modelBuilder.Entity("WebAPI.Database.Entities.Image", b =>
                {
                    b.HasOne("WebAPI.Database.Entities.GroupImage", "GroupImage")
                        .WithMany("Images")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GroupImage");
                });

            modelBuilder.Entity("WebAPI.Database.Entities.GroupImage", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("WebAPI.Database.Entities.User", b =>
                {
                    b.Navigation("GroupImage");
                });
#pragma warning restore 612, 618
        }
    }
}
